### ISSUE TITLE
Line container can solve CSA Squared Ends

### ISSUE THREAD

**Issue by mickeyandkaka** [bqi343/USACO#16]
In https://github.com/bqi343/USACO/blob/master/Implementations/content/data-structures/STL%20(5)/LCnew.h
said  " CSA Squared Ends not working :("
but I managed to solve it using kactl line container...
My submission is [here](https://csacademy.com/code/tqtLIlGf/)

**Comment by bqi343** [comment]
I meant that at some point in time CSAcademy wasn't letting me submit :)
