### ISSUE TITLE
Fix Bug at Binary Search 

### ISSUE THREAD

**Issue by mohanadtalat91** [bqi343/USACO#20]
Overflow will be happen at this line because if "lo = 2147483647" & "hi = 1" then the sum of "lo"+"hi" will be overflow. 
So try to use the following formula to prevent overflow - - > " mid = lo + ((hi-lo)/2) "

I'll add PR. 

https://github.com/bqi343/USACO/blob/26d1428ccd789e2b87c8e34f217f3d711d45fc35/Other%20Implementations/04%20-%20Sorting%20and%20Searching/Binary%20Search%20(4.3).cpp#L10

**Comment by bqi343** [comment]
`hi-lo` could overflow as well. In C++20, you can use https://codeforces.com/blog/entry/96040?#comment-851220. Anyways, the point of that snippet is just to solve https://open.kattis.com/problems/guess, so it doesn't really matter.
