### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by JefferyVin** [bqi343/USACO#6]
Hi Benjamin Congratulations for placing first in IOI. Can you share some of your templates and reading list? I really want to each plat this year in USACO.

**Comment by bqi343** [comment]
Isn't this already on the Github?

**Comment by JefferyVin** [comment]
template <class T> using Tree = tree<T, null_type, less<T>, rb_tree_tag,tree_order_statistics_node_update>;
What is this line used for?

**Comment by bqi343** [comment]
see the README

**Comment by JefferyVin** [comment]
Kk

**Comment by JefferyVin** [comment]
Benjamin how do you include install/implement multilib on mac? Or did u just used ubuntu instead?

**Comment by bqi343** [comment]
I don't know what that is.

**Comment by JefferyVin** [comment]
#include <bits/stdc++.h>
#include <ext/pb_ds/tree_policy.hpp>
#include <ext/pb_ds/assoc_container.hpp>
#include <ext/rope>

**Comment by JefferyVin** [comment]
Are you competing this weekend? If you are, good luck!

**Comment by bqi343** [comment]
I didn't do anything extra to install them.

**Comment by JefferyVin** [comment]
What os r u on?

**Comment by bqi343** [comment]
Mac

**Comment by JefferyVin** [comment]
Wuhhhhh same

**Comment by Chillee** [comment]
@JefferyVin These are included in GCC, but not Clang. If you are on Mac, the gcc command is actually clang by default. You need to install gcc yourself.

**Comment by JefferyVin** [comment]
ya, I was accidentally using clang, now using gnu properly
